# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.apps.zuoyepigai import archive_pb2 as yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/apps/zuoyepigai/archive_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ArchiveStub(object):
    """*
    档案管理
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Archive/List",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveListRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveListResponse.FromString,
            _registered_method=True,
        )
        self.Detail = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Archive/Detail",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailResponse.FromString,
            _registered_method=True,
        )
        self.DetailByStudentDid = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Archive/DetailByStudentDid",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailStudentRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailStudentResponse.FromString,
            _registered_method=True,
        )
        self.Add = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Archive/Add",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveAddRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveAddResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Archive/Delete",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDeleteRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDeleteResponse.FromString,
            _registered_method=True,
        )
        self.Update = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Archive/Update",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveUpdateRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveUpdateResponse.FromString,
            _registered_method=True,
        )


class ArchiveServicer(object):
    """*
    档案管理
    """

    def List(self, request, context):
        """列表"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Detail(self, request, context):
        """详情：老师调用，根据 uid 主键查询"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DetailByStudentDid(self, request, context):
        """详情：学生调用，根据 studentDid 调用"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Add(self, request, context):
        """添加"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """删除"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """修改"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ArchiveServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveListRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveListResponse.SerializeToString,
        ),
        "Detail": grpc.unary_unary_rpc_method_handler(
            servicer.Detail,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailResponse.SerializeToString,
        ),
        "DetailByStudentDid": grpc.unary_unary_rpc_method_handler(
            servicer.DetailByStudentDid,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailStudentRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailStudentResponse.SerializeToString,
        ),
        "Add": grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveAddRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveAddResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDeleteRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDeleteResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveUpdateRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveUpdateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.apps.zuoyepigai.Archive", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.apps.zuoyepigai.Archive", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Archive(object):
    """*
    档案管理
    """

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Archive/List",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveListRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Detail(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Archive/Detail",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DetailByStudentDid(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Archive/DetailByStudentDid",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailStudentRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDetailStudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Add(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Archive/Add",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveAddRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Archive/Delete",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDeleteRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Archive/Update",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveUpdateRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_archive__pb2.ArchiveUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
