# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.apps.zuoyepigai import message_pb2 as yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/apps/zuoyepigai/message_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MessageStub(object):
    """*
    消息盒子
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Message/List",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MessageListRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MessageListResponse.FromString,
            _registered_method=True,
        )
        self.Count = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Message/Count",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.CountRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.CountResponse.FromString,
            _registered_method=True,
        )
        self.ListBy = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Message/ListBy",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.ListByRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.ListByResponse.FromString,
            _registered_method=True,
        )
        self.MarkAsRead = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Message/MarkAsRead",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MarkAsReadRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MarkAsReadResponse.FromString,
            _registered_method=True,
        )


class MessageServicer(object):
    """*
    消息盒子
    """

    def List(self, request, context):
        """列表"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Count(self, request, context):
        """查询消息数量"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListBy(self, request, context):
        """根据状态查询消息已读数量和未读数量"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MarkAsRead(self, request, context):
        """标记为已读"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MessageListRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MessageListResponse.SerializeToString,
        ),
        "Count": grpc.unary_unary_rpc_method_handler(
            servicer.Count,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.CountRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.CountResponse.SerializeToString,
        ),
        "ListBy": grpc.unary_unary_rpc_method_handler(
            servicer.ListBy,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.ListByRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.ListByResponse.SerializeToString,
        ),
        "MarkAsRead": grpc.unary_unary_rpc_method_handler(
            servicer.MarkAsRead,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MarkAsReadRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MarkAsReadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.apps.zuoyepigai.Message", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.apps.zuoyepigai.Message", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Message(object):
    """*
    消息盒子
    """

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Message/List",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MessageListRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MessageListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Count(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Message/Count",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.CountRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListBy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Message/ListBy",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.ListByRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.ListByResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MarkAsRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Message/MarkAsRead",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MarkAsReadRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_message__pb2.MarkAsReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
