# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.apps.zuoyepigai import task_pb2 as yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/apps/zuoyepigai/task_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TaskStub(object):
    """*
    老师教学任务管理
    对应的 DB 表：zuoyepigai.teaching_tasks
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Task/Add",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.AddTaskRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.AddTaskResponse.FromString,
            _registered_method=True,
        )
        self.Detail = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Task/Detail",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DetailTaskRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DetailTaskResponse.FromString,
            _registered_method=True,
        )
        self.List = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Task/List",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.ListTaskRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.ListTaskResponse.FromString,
            _registered_method=True,
        )
        self.TagCount = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Task/TagCount",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.TagCountTaskRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.TagCountTaskResponse.FromString,
            _registered_method=True,
        )
        self.Update = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Task/Update",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.UpdateTaskRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.UpdateTaskResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/yeying.api.apps.zuoyepigai.Task/Delete",
            request_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DeleteTaskRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DeleteTaskResponse.FromString,
            _registered_method=True,
        )


class TaskServicer(object):
    """*
    老师教学任务管理
    对应的 DB 表：zuoyepigai.teaching_tasks
    """

    def Add(self, request, context):
        """创建任务：由老师负创建教学任务"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Detail(self, request, context):
        """任务详情"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """查询老师名下总的任务列表"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TagCount(self, request, context):
        """查询老师名下创建的 tag 名下对应的任务数量"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """更新任务"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """删除任务"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TaskServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Add": grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.AddTaskRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.AddTaskResponse.SerializeToString,
        ),
        "Detail": grpc.unary_unary_rpc_method_handler(
            servicer.Detail,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DetailTaskRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DetailTaskResponse.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.ListTaskRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.ListTaskResponse.SerializeToString,
        ),
        "TagCount": grpc.unary_unary_rpc_method_handler(
            servicer.TagCount,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.TagCountTaskRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.TagCountTaskResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.UpdateTaskRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.UpdateTaskResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DeleteTaskRequest.FromString,
            response_serializer=yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DeleteTaskResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.apps.zuoyepigai.Task", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.apps.zuoyepigai.Task", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Task(object):
    """*
    老师教学任务管理
    对应的 DB 表：zuoyepigai.teaching_tasks
    """

    @staticmethod
    def Add(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Task/Add",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.AddTaskRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.AddTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Detail(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Task/Detail",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DetailTaskRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DetailTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Task/List",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.ListTaskRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.ListTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TagCount(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Task/TagCount",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.TagCountTaskRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.TagCountTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Task/Update",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.UpdateTaskRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.UpdateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.apps.zuoyepigai.Task/Delete",
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DeleteTaskRequest.SerializeToString,
            yeying_dot_api_dot_apps_dot_zuoyepigai_dot_task__pb2.DeleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
