# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.spider import spider_pb2 as yeying_dot_api_dot_spider_dot_spider__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/spider/spider_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SpiderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
            "/yeying.api.plugin.Spider/Search",
            request_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.SearchRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.SearchResponse.FromString,
            _registered_method=True,
        )
        self.Install = channel.unary_unary(
            "/yeying.api.plugin.Spider/Install",
            request_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallResponse.FromString,
            _registered_method=True,
        )
        self.Upgrade = channel.unary_unary(
            "/yeying.api.plugin.Spider/Upgrade",
            request_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallResponse.FromString,
            _registered_method=True,
        )
        self.Config = channel.unary_unary(
            "/yeying.api.plugin.Spider/Config",
            request_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallResponse.FromString,
            _registered_method=True,
        )
        self.Remove = channel.unary_unary(
            "/yeying.api.plugin.Spider/Remove",
            request_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.UninstallRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.UninstallResponse.FromString,
            _registered_method=True,
        )


class SpiderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """搜索"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Install(self, request, context):
        """安装"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Upgrade(self, request, context):
        """升级"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Config(self, request, context):
        """配置"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Remove(self, request, context):
        """卸载"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SpiderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.SearchRequest.FromString,
            response_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.SearchResponse.SerializeToString,
        ),
        "Install": grpc.unary_unary_rpc_method_handler(
            servicer.Install,
            request_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallRequest.FromString,
            response_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallResponse.SerializeToString,
        ),
        "Upgrade": grpc.unary_unary_rpc_method_handler(
            servicer.Upgrade,
            request_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallRequest.FromString,
            response_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallResponse.SerializeToString,
        ),
        "Config": grpc.unary_unary_rpc_method_handler(
            servicer.Config,
            request_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallRequest.FromString,
            response_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.InstallResponse.SerializeToString,
        ),
        "Remove": grpc.unary_unary_rpc_method_handler(
            servicer.Remove,
            request_deserializer=yeying_dot_api_dot_spider_dot_spider__pb2.UninstallRequest.FromString,
            response_serializer=yeying_dot_api_dot_spider_dot_spider__pb2.UninstallResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.plugin.Spider", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.plugin.Spider", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Spider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.plugin.Spider/Search",
            yeying_dot_api_dot_spider_dot_spider__pb2.SearchRequest.SerializeToString,
            yeying_dot_api_dot_spider_dot_spider__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Install(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.plugin.Spider/Install",
            yeying_dot_api_dot_spider_dot_spider__pb2.InstallRequest.SerializeToString,
            yeying_dot_api_dot_spider_dot_spider__pb2.InstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Upgrade(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.plugin.Spider/Upgrade",
            yeying_dot_api_dot_spider_dot_spider__pb2.InstallRequest.SerializeToString,
            yeying_dot_api_dot_spider_dot_spider__pb2.InstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Config(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.plugin.Spider/Config",
            yeying_dot_api_dot_spider_dot_spider__pb2.InstallRequest.SerializeToString,
            yeying_dot_api_dot_spider_dot_spider__pb2.InstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Remove(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.plugin.Spider/Remove",
            yeying_dot_api_dot_spider_dot_spider__pb2.UninstallRequest.SerializeToString,
            yeying_dot_api_dot_spider_dot_spider__pb2.UninstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
