# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.spider import topic_pb2 as yeying_dot_api_dot_spider_dot_topic__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/spider/topic_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TopicStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
            "/yeying.api.topic.Topic/Search",
            request_serializer=yeying_dot_api_dot_spider_dot_topic__pb2.SearchRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_spider_dot_topic__pb2.SearchResponse.FromString,
            _registered_method=True,
        )
        self.Subscribe = channel.unary_unary(
            "/yeying.api.topic.Topic/Subscribe",
            request_serializer=yeying_dot_api_dot_spider_dot_topic__pb2.SubscribeRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_spider_dot_topic__pb2.SubscribeResponse.FromString,
            _registered_method=True,
        )
        self.Unsubscribe = channel.unary_unary(
            "/yeying.api.topic.Topic/Unsubscribe",
            request_serializer=yeying_dot_api_dot_spider_dot_topic__pb2.UnsubscribeRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_spider_dot_topic__pb2.UnsubscribeResponse.FromString,
            _registered_method=True,
        )


class TopicServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """搜索订阅"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Subscribe(self, request, context):
        """订阅"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Unsubscribe(self, request, context):
        """取消订阅"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TopicServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=yeying_dot_api_dot_spider_dot_topic__pb2.SearchRequest.FromString,
            response_serializer=yeying_dot_api_dot_spider_dot_topic__pb2.SearchResponse.SerializeToString,
        ),
        "Subscribe": grpc.unary_unary_rpc_method_handler(
            servicer.Subscribe,
            request_deserializer=yeying_dot_api_dot_spider_dot_topic__pb2.SubscribeRequest.FromString,
            response_serializer=yeying_dot_api_dot_spider_dot_topic__pb2.SubscribeResponse.SerializeToString,
        ),
        "Unsubscribe": grpc.unary_unary_rpc_method_handler(
            servicer.Unsubscribe,
            request_deserializer=yeying_dot_api_dot_spider_dot_topic__pb2.UnsubscribeRequest.FromString,
            response_serializer=yeying_dot_api_dot_spider_dot_topic__pb2.UnsubscribeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.topic.Topic", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.topic.Topic", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Topic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.topic.Topic/Search",
            yeying_dot_api_dot_spider_dot_topic__pb2.SearchRequest.SerializeToString,
            yeying_dot_api_dot_spider_dot_topic__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Subscribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.topic.Topic/Subscribe",
            yeying_dot_api_dot_spider_dot_topic__pb2.SubscribeRequest.SerializeToString,
            yeying_dot_api_dot_spider_dot_topic__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Unsubscribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.topic.Topic/Unsubscribe",
            yeying_dot_api_dot_spider_dot_topic__pb2.UnsubscribeRequest.SerializeToString,
            yeying_dot_api_dot_spider_dot_topic__pb2.UnsubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
