# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.content import content_pb2 as yeying_dot_api_dot_content_dot_content__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/content/content_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ContentStub(object):
    """检查内容是否合规，为了保护数据隐私，要么是tee，要么是同态"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.validate = channel.unary_unary(
            "/yeying.api.content.Content/validate",
            request_serializer=yeying_dot_api_dot_content_dot_content__pb2.ValidateRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_content_dot_content__pb2.ValidateResponse.FromString,
            _registered_method=True,
        )


class ContentServicer(object):
    """检查内容是否合规，为了保护数据隐私，要么是tee，要么是同态"""

    def validate(self, request, context):
        """身份托管"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ContentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "validate": grpc.unary_unary_rpc_method_handler(
            servicer.validate,
            request_deserializer=yeying_dot_api_dot_content_dot_content__pb2.ValidateRequest.FromString,
            response_serializer=yeying_dot_api_dot_content_dot_content__pb2.ValidateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.content.Content", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.content.Content", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Content(object):
    """检查内容是否合规，为了保护数据隐私，要么是tee，要么是同态"""

    @staticmethod
    def validate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.content.Content/validate",
            yeying_dot_api_dot_content_dot_content__pb2.ValidateRequest.SerializeToString,
            yeying_dot_api_dot_content_dot_content__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
