# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.event import event_pb2 as yeying_dot_api_dot_event_dot_event__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/event/event_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EventStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Produce = channel.unary_unary(
            "/yeying.api.event.Event/Produce",
            request_serializer=yeying_dot_api_dot_event_dot_event__pb2.ProduceRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_event_dot_event__pb2.ProduceResponse.FromString,
            _registered_method=True,
        )
        self.Consume = channel.unary_unary(
            "/yeying.api.event.Event/Consume",
            request_serializer=yeying_dot_api_dot_event_dot_event__pb2.ConsumeRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_event_dot_event__pb2.ConsumeResponse.FromString,
            _registered_method=True,
        )


class EventServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Produce(self, request, context):
        """某个服务作为客户端生成了事件，通常node会实现服务端，然后同步给用户"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Consume(self, request, context):
        """用户直接向生成事件的服务消费并给出处理意见"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EventServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Produce": grpc.unary_unary_rpc_method_handler(
            servicer.Produce,
            request_deserializer=yeying_dot_api_dot_event_dot_event__pb2.ProduceRequest.FromString,
            response_serializer=yeying_dot_api_dot_event_dot_event__pb2.ProduceResponse.SerializeToString,
        ),
        "Consume": grpc.unary_unary_rpc_method_handler(
            servicer.Consume,
            request_deserializer=yeying_dot_api_dot_event_dot_event__pb2.ConsumeRequest.FromString,
            response_serializer=yeying_dot_api_dot_event_dot_event__pb2.ConsumeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.event.Event", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.event.Event", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Event(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Produce(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.event.Event/Produce",
            yeying_dot_api_dot_event_dot_event__pb2.ProduceRequest.SerializeToString,
            yeying_dot_api_dot_event_dot_event__pb2.ProduceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Consume(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.event.Event/Consume",
            yeying_dot_api_dot_event_dot_event__pb2.ConsumeRequest.SerializeToString,
            yeying_dot_api_dot_event_dot_event__pb2.ConsumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
