# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.mail import mail_pb2 as yeying_dot_api_dot_mail_dot_mail__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/mail/mail_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MailStub(object):
    """*
    定义一个邮件服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
            "/yeying.api.mail.Mail/Send",
            request_serializer=yeying_dot_api_dot_mail_dot_mail__pb2.SendMailRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_mail_dot_mail__pb2.SendMailResponse.FromString,
            _registered_method=True,
        )
        self.Verify = channel.unary_unary(
            "/yeying.api.mail.Mail/Verify",
            request_serializer=yeying_dot_api_dot_mail_dot_mail__pb2.VerifyMailRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_mail_dot_mail__pb2.VerifyMailResponse.FromString,
            _registered_method=True,
        )


class MailServicer(object):
    """*
    定义一个邮件服务
    """

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MailServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Send": grpc.unary_unary_rpc_method_handler(
            servicer.Send,
            request_deserializer=yeying_dot_api_dot_mail_dot_mail__pb2.SendMailRequest.FromString,
            response_serializer=yeying_dot_api_dot_mail_dot_mail__pb2.SendMailResponse.SerializeToString,
        ),
        "Verify": grpc.unary_unary_rpc_method_handler(
            servicer.Verify,
            request_deserializer=yeying_dot_api_dot_mail_dot_mail__pb2.VerifyMailRequest.FromString,
            response_serializer=yeying_dot_api_dot_mail_dot_mail__pb2.VerifyMailResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.mail.Mail", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.mail.Mail", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Mail(object):
    """*
    定义一个邮件服务
    """

    @staticmethod
    def Send(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.mail.Mail/Send",
            yeying_dot_api_dot_mail_dot_mail__pb2.SendMailRequest.SerializeToString,
            yeying_dot_api_dot_mail_dot_mail__pb2.SendMailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Verify(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.mail.Mail/Verify",
            yeying_dot_api_dot_mail_dot_mail__pb2.VerifyMailRequest.SerializeToString,
            yeying_dot_api_dot_mail_dot_mail__pb2.VerifyMailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
