# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.service import service_pb2 as yeying_dot_api_dot_service_dot_service__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/service/service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ServiceStub(object):
    """*
    节点提供服务创建、上线、下线和查询的服务。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/yeying.api.service.Service/Create",
            request_serializer=yeying_dot_api_dot_service_dot_service__pb2.CreateServiceRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_service_dot_service__pb2.CreateServiceResponse.FromString,
            _registered_method=True,
        )
        self.Detail = channel.unary_unary(
            "/yeying.api.service.Service/Detail",
            request_serializer=yeying_dot_api_dot_service_dot_service__pb2.DetailServiceRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_service_dot_service__pb2.DetailServiceResponse.FromString,
            _registered_method=True,
        )
        self.Search = channel.unary_unary(
            "/yeying.api.service.Service/Search",
            request_serializer=yeying_dot_api_dot_service_dot_service__pb2.SearchServiceRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_service_dot_service__pb2.SearchServiceResponse.FromString,
            _registered_method=True,
        )
        self.Online = channel.unary_unary(
            "/yeying.api.service.Service/Online",
            request_serializer=yeying_dot_api_dot_service_dot_service__pb2.OnlineServiceRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_service_dot_service__pb2.OnlineServiceResponse.FromString,
            _registered_method=True,
        )
        self.Offline = channel.unary_unary(
            "/yeying.api.service.Service/Offline",
            request_serializer=yeying_dot_api_dot_service_dot_service__pb2.OfflineServiceRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_service_dot_service__pb2.OfflineServiceResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/yeying.api.service.Service/Delete",
            request_serializer=yeying_dot_api_dot_service_dot_service__pb2.DeleteServiceRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_service_dot_service__pb2.DeleteServiceResponse.FromString,
            _registered_method=True,
        )


class ServiceServicer(object):
    """*
    节点提供服务创建、上线、下线和查询的服务。
    """

    def Create(self, request, context):
        """服务创建"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Detail(self, request, context):
        """服务详情"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Search(self, request, context):
        """搜索服务"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Online(self, request, context):
        """上线服务"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Offline(self, request, context):
        """下线服务"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """删除服务"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=yeying_dot_api_dot_service_dot_service__pb2.CreateServiceRequest.FromString,
            response_serializer=yeying_dot_api_dot_service_dot_service__pb2.CreateServiceResponse.SerializeToString,
        ),
        "Detail": grpc.unary_unary_rpc_method_handler(
            servicer.Detail,
            request_deserializer=yeying_dot_api_dot_service_dot_service__pb2.DetailServiceRequest.FromString,
            response_serializer=yeying_dot_api_dot_service_dot_service__pb2.DetailServiceResponse.SerializeToString,
        ),
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=yeying_dot_api_dot_service_dot_service__pb2.SearchServiceRequest.FromString,
            response_serializer=yeying_dot_api_dot_service_dot_service__pb2.SearchServiceResponse.SerializeToString,
        ),
        "Online": grpc.unary_unary_rpc_method_handler(
            servicer.Online,
            request_deserializer=yeying_dot_api_dot_service_dot_service__pb2.OnlineServiceRequest.FromString,
            response_serializer=yeying_dot_api_dot_service_dot_service__pb2.OnlineServiceResponse.SerializeToString,
        ),
        "Offline": grpc.unary_unary_rpc_method_handler(
            servicer.Offline,
            request_deserializer=yeying_dot_api_dot_service_dot_service__pb2.OfflineServiceRequest.FromString,
            response_serializer=yeying_dot_api_dot_service_dot_service__pb2.OfflineServiceResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=yeying_dot_api_dot_service_dot_service__pb2.DeleteServiceRequest.FromString,
            response_serializer=yeying_dot_api_dot_service_dot_service__pb2.DeleteServiceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.service.Service", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.service.Service", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Service(object):
    """*
    节点提供服务创建、上线、下线和查询的服务。
    """

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.service.Service/Create",
            yeying_dot_api_dot_service_dot_service__pb2.CreateServiceRequest.SerializeToString,
            yeying_dot_api_dot_service_dot_service__pb2.CreateServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Detail(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.service.Service/Detail",
            yeying_dot_api_dot_service_dot_service__pb2.DetailServiceRequest.SerializeToString,
            yeying_dot_api_dot_service_dot_service__pb2.DetailServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.service.Service/Search",
            yeying_dot_api_dot_service_dot_service__pb2.SearchServiceRequest.SerializeToString,
            yeying_dot_api_dot_service_dot_service__pb2.SearchServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Online(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.service.Service/Online",
            yeying_dot_api_dot_service_dot_service__pb2.OnlineServiceRequest.SerializeToString,
            yeying_dot_api_dot_service_dot_service__pb2.OnlineServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Offline(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.service.Service/Offline",
            yeying_dot_api_dot_service_dot_service__pb2.OfflineServiceRequest.SerializeToString,
            yeying_dot_api_dot_service_dot_service__pb2.OfflineServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.service.Service/Delete",
            yeying_dot_api_dot_service_dot_service__pb2.DeleteServiceRequest.SerializeToString,
            yeying_dot_api_dot_service_dot_service__pb2.DeleteServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
