# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.service import service_pb2 as yeying_dot_api_dot_service_dot_service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in yeying/api/service/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceStub(object):
    """*
    节点提供服务登记、注销和查询的服务。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/yeying.api.service.Service/Register',
                request_serializer=yeying_dot_api_dot_service_dot_service__pb2.RegisterServiceRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_service_dot_service__pb2.RegisterServiceResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/yeying.api.service.Service/Search',
                request_serializer=yeying_dot_api_dot_service_dot_service__pb2.SearchServiceRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_service_dot_service__pb2.SearchServiceResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/yeying.api.service.Service/Unregister',
                request_serializer=yeying_dot_api_dot_service_dot_service__pb2.UnregisterServiceRequest.SerializeToString,
                response_deserializer=yeying_dot_api_dot_service_dot_service__pb2.UnregisterServiceResponse.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """*
    节点提供服务登记、注销和查询的服务。
    """

    def Register(self, request, context):
        """注册服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """搜索服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """注销服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=yeying_dot_api_dot_service_dot_service__pb2.RegisterServiceRequest.FromString,
                    response_serializer=yeying_dot_api_dot_service_dot_service__pb2.RegisterServiceResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=yeying_dot_api_dot_service_dot_service__pb2.SearchServiceRequest.FromString,
                    response_serializer=yeying_dot_api_dot_service_dot_service__pb2.SearchServiceResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=yeying_dot_api_dot_service_dot_service__pb2.UnregisterServiceRequest.FromString,
                    response_serializer=yeying_dot_api_dot_service_dot_service__pb2.UnregisterServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yeying.api.service.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yeying.api.service.Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """*
    节点提供服务登记、注销和查询的服务。
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.service.Service/Register',
            yeying_dot_api_dot_service_dot_service__pb2.RegisterServiceRequest.SerializeToString,
            yeying_dot_api_dot_service_dot_service__pb2.RegisterServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.service.Service/Search',
            yeying_dot_api_dot_service_dot_service__pb2.SearchServiceRequest.SerializeToString,
            yeying_dot_api_dot_service_dot_service__pb2.SearchServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yeying.api.service.Service/Unregister',
            yeying_dot_api_dot_service_dot_service__pb2.UnregisterServiceRequest.SerializeToString,
            yeying_dot_api_dot_service_dot_service__pb2.UnregisterServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
