# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.node import node_pb2 as yeying_dot_api_dot_node_dot_node__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/node/node_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class NodeStub(object):
    """*
    每一个服务都是一个节点，提供通用的接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
            "/yeying.api.node.Node/HealthCheck",
            request_serializer=yeying_dot_api_dot_node_dot_node__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_node_dot_node__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.Whoami = channel.unary_unary(
            "/yeying.api.node.Node/Whoami",
            request_serializer=yeying_dot_api_dot_node_dot_node__pb2.WhoamiRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_node_dot_node__pb2.WhoamiResponse.FromString,
            _registered_method=True,
        )


class NodeServicer(object):
    """*
    每一个服务都是一个节点，提供通用的接口
    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Whoami(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=yeying_dot_api_dot_node_dot_node__pb2.HealthCheckRequest.FromString,
            response_serializer=yeying_dot_api_dot_node_dot_node__pb2.HealthCheckResponse.SerializeToString,
        ),
        "Whoami": grpc.unary_unary_rpc_method_handler(
            servicer.Whoami,
            request_deserializer=yeying_dot_api_dot_node_dot_node__pb2.WhoamiRequest.FromString,
            response_serializer=yeying_dot_api_dot_node_dot_node__pb2.WhoamiResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.node.Node", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.node.Node", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Node(object):
    """*
    每一个服务都是一个节点，提供通用的接口
    """

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.node.Node/HealthCheck",
            yeying_dot_api_dot_node_dot_node__pb2.HealthCheckRequest.SerializeToString,
            yeying_dot_api_dot_node_dot_node__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Whoami(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.node.Node/Whoami",
            yeying_dot_api_dot_node_dot_node__pb2.WhoamiRequest.SerializeToString,
            yeying_dot_api_dot_node_dot_node__pb2.WhoamiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
