# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.support import support_pb2 as yeying_dot_api_dot_support_dot_support__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/support/support_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SupportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Collect = channel.unary_unary(
            "/yeying.api.support.Support/Collect",
            request_serializer=yeying_dot_api_dot_support_dot_support__pb2.CollectSupportRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_support_dot_support__pb2.CollectSupportResponse.FromString,
            _registered_method=True,
        )


class SupportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Collect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SupportServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Collect": grpc.unary_unary_rpc_method_handler(
            servicer.Collect,
            request_deserializer=yeying_dot_api_dot_support_dot_support__pb2.CollectSupportRequest.FromString,
            response_serializer=yeying_dot_api_dot_support_dot_support__pb2.CollectSupportResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.api.support.Support", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.api.support.Support", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Support(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Collect(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.api.support.Support/Collect",
            yeying_dot_api_dot_support_dot_support__pb2.CollectSupportRequest.SerializeToString,
            yeying_dot_api_dot_support_dot_support__pb2.CollectSupportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
