# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yeying.api.network import registry_pb2 as yeying_dot_api_dot_network_dot_registry__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in yeying/api/network/registry_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class NetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
            "/yeying.network.Network/List",
            request_serializer=yeying_dot_api_dot_network_dot_registry__pb2.ListRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_network_dot_registry__pb2.ListResponse.FromString,
            _registered_method=True,
        )
        self.Join = channel.unary_unary(
            "/yeying.network.Network/Join",
            request_serializer=yeying_dot_api_dot_network_dot_registry__pb2.JoinRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_network_dot_registry__pb2.JoinResponse.FromString,
            _registered_method=True,
        )
        self.Exit = channel.unary_unary(
            "/yeying.network.Network/Exit",
            request_serializer=yeying_dot_api_dot_network_dot_registry__pb2.ExitRequest.SerializeToString,
            response_deserializer=yeying_dot_api_dot_network_dot_registry__pb2.ExitResponse.FromString,
            _registered_method=True,
        )


class NetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Exit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=yeying_dot_api_dot_network_dot_registry__pb2.ListRequest.FromString,
            response_serializer=yeying_dot_api_dot_network_dot_registry__pb2.ListResponse.SerializeToString,
        ),
        "Join": grpc.unary_unary_rpc_method_handler(
            servicer.Join,
            request_deserializer=yeying_dot_api_dot_network_dot_registry__pb2.JoinRequest.FromString,
            response_serializer=yeying_dot_api_dot_network_dot_registry__pb2.JoinResponse.SerializeToString,
        ),
        "Exit": grpc.unary_unary_rpc_method_handler(
            servicer.Exit,
            request_deserializer=yeying_dot_api_dot_network_dot_registry__pb2.ExitRequest.FromString,
            response_serializer=yeying_dot_api_dot_network_dot_registry__pb2.ExitResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("yeying.network.Network", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("yeying.network.Network", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Network(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.network.Network/List",
            yeying_dot_api_dot_network_dot_registry__pb2.ListRequest.SerializeToString,
            yeying_dot_api_dot_network_dot_registry__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Join(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.network.Network/Join",
            yeying_dot_api_dot_network_dot_registry__pb2.JoinRequest.SerializeToString,
            yeying_dot_api_dot_network_dot_registry__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Exit(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/yeying.network.Network/Exit",
            yeying_dot_api_dot_network_dot_registry__pb2.ExitRequest.SerializeToString,
            yeying_dot_api_dot_network_dot_registry__pb2.ExitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
